### ISSUE TITLE
Code quality

### ISSUE THREAD

**Issue by tarampampam** [jannejava/laravel-json#3]
Hi @jannejava!

Thanks for your package! But I cannot use it in my projects, because code quality is not good. So, I wrote one more wrapper (json), and maybe you can take some ideas for your code refactoring.

Link: https://github.com/tarampampam/wrappers-php

-----

> Sorry for my english.

**Comment by svenluijten** [comment]
Why not submit a PR to improve the code quality of this existing package then? 🙂

**Comment by tarampampam** [comment]
Because PR would overwrite 90% of existing code :(

**Comment by svenluijten** [comment]
You mean like #2? 😉

**Comment by tarampampam** [comment]
Yeah :D

**Comment by jannejava** [comment]
Come on! Don't be shy! It has already happened once :-)

In essence, we are only talking about variants of:

```

$array = json_decode($string);

if(json_last_error() != JSON_ERROR_NONE) {
   throw \Exeception
}

```
